spring:
  config:
    activate:
      on-profile: "prod"


build:
  version: "1.0"

accounts:
  message: "Welcome to EazyBank loans related prod APIs "
  contactDetails:
    name: "Reine Ray - QA Lead"
    email: "smitha@eazybank.com"
  onCallSupport:
    - (435) 555-1234
    - (666) 523-1345