spring:
  application:
    name: configserver
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: "file:../accounts/src/main/resources/config"
server:
  port: 8071